In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/play-store-dataset/apps.csv
/kaggle/input/play-store-dataset/user_reviews.csv


**Importing Dependecies**

In [2]:
import plotly.express as px
from matplotlib import pyplot as plt
import seaborn as sns

**Load Apps Data to the Data Frame**

In [3]:
apps = pd.read_csv('/kaggle/input/play-store-dataset/apps.csv')

In [4]:
# Check the top 5 rows with the labels of the App data
apps.head()

Unnamed: 0                                                App  \
0           0     Photo Editor & Candy Camera & Grid & ScrapBook   
1           1                                Coloring book moana   
2           2  U Launcher Lite – FREE Live Cool Themes, Hide ...   
3           3                              Sketch - Draw & Paint   
4           4              Pixel Draw - Number Art Coloring Book   

         Category  Rating  Reviews  Size     Installs  Type Price  \
0  ART_AND_DESIGN     4.1      159   19M      10,000+  Free     0   
1  ART_AND_DESIGN     3.9      967   14M     500,000+  Free     0   
2  ART_AND_DESIGN     4.7    87510  8.7M   5,000,000+  Free     0   
3  ART_AND_DESIGN     4.5   215644   25M  50,000,000+  Free     0   
4  ART_AND_DESIGN     4.3      967  2.8M     100,000+  Free     0   

  Content Rating                     Genres      Last Updated  \
0       Everyone               Art & Design   January 7, 2018   
1       Everyone  Art & Design;Pretend Play  January 15, 2018   
2       Everyone               Art & Design    August 1, 2018   
3           Teen               Art & Design      June 8, 2018   
4       Everyone    Art & Design;Creativity     June 20, 2018   

          Current Ver   Android Ver  
0               1.0.0  4.0.3 and up  
1               2.0.0  4.0.3 and up  
2               1.2.4  4.0.3 and up  
3  Varies with device    4.2 and up  
4                 1.1    4.4 and up

In [5]:
# Cannot decide what the 'unnamed: 0 ' represent to the data on that, drop it.

apps = apps.iloc[:,1:]
apps.head()

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

   Reviews  Size     Installs  Type Price Content Rating  \
0      159   19M      10,000+  Free     0       Everyone   
1      967   14M     500,000+  Free     0       Everyone   
2    87510  8.7M   5,000,000+  Free     0       Everyone   
3   215644   25M  50,000,000+  Free     0           Teen   
4      967  2.8M     100,000+  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

**Check for missing values**

In [6]:
# columns of the App data with missing values

apps.isna().any()

App               False
Category          False
Rating             True
Reviews           False
Size               True
Installs          False
Type               True
Price             False
Content Rating    False
Genres            False
Last Updated      False
Current Ver        True
Android Ver        True
dtype: bool

In [7]:
# The number of Missing values in the App data
apps.isna().sum()

App                  0
Category             0
Rating            1463
Reviews              0
Size              1227
Installs             0
Type                 1
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver          2
dtype: int64

In [8]:
# columns with missing values

missing_value_col = [col for col in apps.columns if apps[col].isna().any() == True]
missing_value_col

['Rating', 'Size', 'Type', 'Current Ver', 'Android Ver']

**Divide the App data into two subset of columns: with missing values and without.**

In [9]:
# apps data that has missing values mv
apps_mv = apps[missing_value_col]
apps_mv.head()

Rating  Size  Type         Current Ver   Android Ver
0     4.1   19M  Free               1.0.0  4.0.3 and up
1     3.9   14M  Free               2.0.0  4.0.3 and up
2     4.7  8.7M  Free               1.2.4  4.0.3 and up
3     4.5   25M  Free  Varies with device    4.2 and up
4     4.3  2.8M  Free                 1.1    4.4 and up

In [10]:
# apps data without missing values wmv
apps_wmv = apps[~ apps.isin(apps_mv)].dropna(axis=1)
apps_wmv.head()

App        Category  Reviews  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN      159   
1                                Coloring book moana  ART_AND_DESIGN      967   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN    87510   
3                              Sketch - Draw & Paint  ART_AND_DESIGN   215644   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN      967   

      Installs Price Content Rating                     Genres  \
0      10,000+     0       Everyone               Art & Design   
1     500,000+     0       Everyone  Art & Design;Pretend Play   
2   5,000,000+     0       Everyone               Art & Design   
3  50,000,000+     0           Teen               Art & Design   
4     100,000+     0       Everyone    Art & Design;Creativity   

       Last Updated  
0   January 7, 2018  
1  January 15, 2018  
2    August 1, 2018  
3      June 8, 2018  
4     June 20, 2018

**Check for duplicates**

In [11]:
apps_wmv.duplicated().any()

False

**EDA**

In [12]:
# apps_wmv data columns overview 
apps_wmv.info()

# convert Last Updated to date format
apps_wmv['Last Updated'] = pd.to_datetime(apps_wmv['Last Updated'])

# convert installs to date interger
apps_wmv['Installs'] = pd.to_numeric(apps_wmv['Installs'].astype(str).str.replace(',','').str.replace('+',''))

# convert Price to date numeric
apps_wmv['Price'] = pd.to_numeric(apps_wmv['Price'].astype(str).str.replace('$',''))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9659 entries, 0 to 9658
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   App             9659 non-null   object
 1   Category        9659 non-null   object
 2   Reviews         9659 non-null   int64 
 3   Installs        9659 non-null   object
 4   Price           9659 non-null   object
 5   Content Rating  9659 non-null   object
 6   Genres          9659 non-null   object
 7   Last Updated    9659 non-null   object
dtypes: int64(1), object(7)
memory usage: 603.8+ KB


In [13]:
apps_wmv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9659 entries, 0 to 9658
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   App             9659 non-null   object        
 1   Category        9659 non-null   object        
 2   Reviews         9659 non-null   int64         
 3   Installs        9659 non-null   int64         
 4   Price           9659 non-null   float64       
 5   Content Rating  9659 non-null   object        
 6   Genres          9659 non-null   object        
 7   Last Updated    9659 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 603.8+ KB


**Category with highest number of Apps**

In [14]:
category_count = apps_wmv.Category.value_counts().reset_index()
fig = px.bar(category_count, x='Category', y='count', color='Category')
fig.show()

/opt/conda/lib/python3.10/site-packages/plotly/express/_core.py:2065: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sf: grouped.get_group(s if len(s) > 1 else s[0])


**Which Category has the heighest number of Installs?**

In [15]:
num_install_cat = apps_wmv.groupby('Category', as_index=False).Installs.sum().sort_values('Installs', ascending=False)
fig = px.bar(num_install_cat, x='Category', y='Installs', color='Category')
fig.show()

/opt/conda/lib/python3.10/site-packages/plotly/express/_core.py:2065: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.



**Apps with their number of Installs in descending order**

In [16]:
install_strenght = apps_wmv.sort_values('Installs', ascending=False)
install_strenght

App             Category   Reviews    Installs  \
300          WhatsApp Messenger        COMMUNICATION  69119316  1000000000   
152           Google Play Books  BOOKS_AND_REFERENCE   1433233  1000000000   
1356             Subway Surfers                 GAME  27722264  1000000000   
2420  Maps - Navigate & Explore     TRAVEL_AND_LOCAL   9235155  1000000000   
304                       Gmail        COMMUNICATION   4604324  1000000000   
...                         ...                  ...       ...         ...   
8763                Eu Sou Rico              FINANCE         0           0   
5661              cronometra-br         PRODUCTIVITY         0           0   
4522     AP Series Solution Pro               FAMILY         0           0   
8577               EP Cook Book              MEDICAL         0           0   
8028  Command & Conquer: Rivals               FAMILY         0           0   

       Price Content Rating             Genres Last Updated  
300     0.00       Everyone      Communication   2018-08-03  
152     0.00           Teen  Books & Reference   2018-08-03  
1356    0.00   Everyone 10+             Arcade   2018-07-12  
2420    0.00       Everyone     Travel & Local   2018-07-31  
304     0.00       Everyone      Communication   2018-08-02  
...      ...            ...                ...          ...  
8763  394.99       Everyone            Finance   2018-07-11  
5661  154.99       Everyone       Productivity   2017-11-24  
4522    1.99       Everyone          Education   2017-07-30  
8577  200.00       Everyone            Medical   2015-07-26  
8028    0.00   Everyone 10+           Strategy   2018-06-28  

[9659 rows x 8 columns]

**Which app is The heighest earning**

In [17]:
apps_wmv['revenue'] = apps_wmv.Installs * apps_wmv.Price
app_revenue = apps_wmv[apps_wmv.revenue > 0].sort_values('revenue', ascending=False)
app_revenue.head()

App   Category  Reviews  Installs   Price  \
1743                      Minecraft     FAMILY  2376564  10000000    6.99   
4396                      I am rich  LIFESTYLE     3547    100000  399.99   
4400              I Am Rich Premium    FINANCE     1867     50000  399.99   
3208                  Hitman Sniper       GAME   408292  10000000    0.99   
6370  Grand Theft Auto: San Andreas       GAME   348962   1000000    6.99   

     Content Rating                     Genres Last Updated     revenue  
1743   Everyone 10+  Arcade;Action & Adventure   2018-07-24  69900000.0  
4396       Everyone                  Lifestyle   2018-01-12  39999000.0  
4400       Everyone                    Finance   2017-11-12  19999500.0  
3208     Mature 17+                     Action   2018-07-12   9900000.0  
6370     Mature 17+                     Action   2015-03-21   6990000.0

**what categories is The heighest earning**

In [18]:
user_reviews = pd.read_csv('/kaggle/input/play-store-dataset/user_reviews.csv')
user_reviews

App  \
0            10 Best Foods for You   
1            10 Best Foods for You   
2            10 Best Foods for You   
3            10 Best Foods for You   
4            10 Best Foods for You   
...                            ...   
64290  Houzz Interior Design Ideas   
64291  Houzz Interior Design Ideas   
64292  Houzz Interior Design Ideas   
64293  Houzz Interior Design Ideas   
64294  Houzz Interior Design Ideas   

                                       Translated_Review Sentiment  \
0      I like eat delicious food. That's I'm cooking ...  Positive   
1        This help eating healthy exercise regular basis  Positive   
2                                                    NaN       NaN   
3             Works great especially going grocery store  Positive   
4                                           Best idea us  Positive   
...                                                  ...       ...   
64290                                                NaN       NaN   
64291                                                NaN       NaN   
64292                                                NaN       NaN   
64293                                                NaN       NaN   
64294                                                NaN       NaN   

       Sentiment_Polarity  Sentiment_Subjectivity  
0                    1.00                0.533333  
1                    0.25                0.288462  
2                     NaN                     NaN  
3                    0.40                0.875000  
4                    1.00                0.300000  
...                   ...                     ...  
64290                 NaN                     NaN  
64291                 NaN                     NaN  
64292                 NaN                     NaN  
64293                 NaN                     NaN  
64294                 NaN                     NaN  

[64295 rows x 5 columns]

In [19]:
app_rev_cat = app_revenue.groupby('Category', as_index=False).count().sort_values('App', ascending=False)
fig = px.bar(app_rev_cat, x='Category', y='App', color='Category')
fig.show()

/opt/conda/lib/python3.10/site-packages/plotly/express/_core.py:2065: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.



## **Sentiment Analysis of Users**

In [20]:
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [21]:
# download stop_word
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [22]:
user_reviews.shape

(64295, 5)

In [23]:
user_reviews = user_reviews.iloc[:, :3].dropna(axis=0)
user_reviews.head()

App                                  Translated_Review  \
0  10 Best Foods for You  I like eat delicious food. That's I'm cooking ...   
1  10 Best Foods for You    This help eating healthy exercise regular basis   
3  10 Best Foods for You         Works great especially going grocery store   
4  10 Best Foods for You                                       Best idea us   
5  10 Best Foods for You                                           Best way   

  Sentiment  
0  Positive  
1  Positive  
3  Positive  
4  Positive  
5  Positive

In [24]:
user_reviews.shape

(37427, 3)

In [25]:
ps = PorterStemmer()

def stemming(content):
    
    stemmed_content = re.sub('[^a-zA-Z]', ' ', content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [ps.stem(word) for word in stemmed_content if not word in set(stopwords.words('english'))]
    stemmed_content = ' '.join(stemmed_content)
    
    return stemmed_content

In [26]:
user_reviews['stemmed_text'] = user_reviews.Translated_Review.astype(str).apply(stemming)

In [27]:
# Seperating the data and label

X = user_reviews.stemmed_text
y = user_reviews.Sentiment

In [28]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2,stratify=y, random_state=10)

In [29]:
## implementing bag of word

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB

cv = CountVectorizer()
train_X = cv.fit_transform(train_X).toarray()
test_X = cv.transform(test_X).toarray()

In [30]:
gnb = BernoulliNB()
gnb.fit(train_X, train_y)

BernoulliNB()

In [31]:
predictions = gnb.predict(test_X)
predictions2 = gnb.predict(train_X)

In [32]:
# check the model score

accuracy_score_train = accuracy_score(train_y, predictions2)
confusion_matrix_train = confusion_matrix(train_y, predictions2)
score_train = gnb.score(train_X, train_y)

print("accuracy_score_X_train: ", accuracy_score_train)
print("confusion_matrix_X_train: ", confusion_matrix_train)
print("score_train: ", score_train)

accuracy_score_test = accuracy_score(test_y, predictions)
confusion_matrix_test = confusion_matrix(test_y, predictions)
score_test = gnb.score(test_X, test_y)

print("\naccuracy_score: ", accuracy_score_test)
print("confusion_matrix: ", confusion_matrix_test)
print("score_test: ", score_test)

accuracy_score_X_train:  0.7741892388363782
confusion_matrix_X_train:  [[ 4123   954  1540]
 [  209  3384   533]
 [ 1446  2079 15673]]
score_train:  0.7741892388363782

accuracy_score:  0.7345711995725354
confusion_matrix:  [[ 906  211  537]
 [  58  782  192]
 [ 451  538 3811]]
score_test:  0.7345711995725354
